security:
    encoders:
        App\Model\User\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fetcher:
            id: App\Security\UserProvider
        # used to reload user from session & other features (e.g. switch_user)
        #app_user_provider:
            #entity:
                #class: App\Model\User\Entity\User
                #property: email
        encoders:
            App\Security\UserIdentity: native
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            anonymous: true
            stateless: true
            user_checker: App\Security\UserChecker
            http_basic:
                provider: fetcher
        main:
            anonymous: lazy
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\OAuth\FacebookAuthenticator
                entry_point: App\Security\FacebookAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            #provider: app_user_provider
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

            form_login: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_MANAGE_USERS
            - ROLE_WORK_MANAGE_MEMBERS
            - ROLE_WORK_MANAGE_PROJECTS
    access_control:
        - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/facebook, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/facebook/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
