version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: nginx-manager
    links:
      - php-fpm
      - php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - php-cli
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=xdebug
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./docker/postgres:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - '54321:5432'
  mailer:
    image: mailhog/mailhog
    ports:
      - "8081:8025"
