version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: nginx-manager
    links:
      - php-fpm
      - manager_php-cli_1
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - manager_php-cli_1
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
  manager_php-cli_1:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
  manager-node-watch:
    image: node:10.13-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  manager-node:
    container_name: api-node
    image: node:10.13-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
  manager-postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./docker/postgres:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - '54321:5432'
  mailer:
    image: mailhog/mailhog
    ports:
      - "8081:8025"
