version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: nginx-manager
    links:
      - php-fpm
      - manager_php-cli_1
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - manager_php-cli_1
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    depends_on:
      - manager-postgres
      - manager-redis
      - mailer
  manager_php-cli_1:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    depends_on:
      - manager-postgres
      - manager-redis
      - mailer
  manager-node-watch:
    image: node:12.0.0
    restart: on-failure
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  manager-node:
    container_name: api-node
    image: node:12.0.0
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
  manager-postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./docker/postgres:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - '54321:5432'
  manager-redis:
    image: redis:3.0-alpine
    volumes:
      - ./docker/redis:/redis
    command: redis-server --requirepass secret

  storage:
    build:
      context: ./storage/docker/development
      dockerfile: nginx.docker
    volumes:
    - ./storage:./www
    ports:
    - "8081:80"
  storage-ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /www
    volumes:
    - ./storage/public:/www
  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"